app = "affiliate-tools-app"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/"
  protocol = "http"
  tls_skip_verify = true

[env]
  PORT = "80"

[deploy]
  strategy = "immediate"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1 