app = "affiliatetoolsapp-test"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    NODE_VERSION = "20"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "3s"
    grace_period = "5s"
    method = "GET"
    path = "/"
    protocol = "http"
    tls_skip_verify = true

[[services.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

[deploy]
  release_command = "npx prisma generate"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
