
app = "your-app-name"  # Replace with your actual app name

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  SUPABASE_URL = "https://jruzfpymzkzegdhmzwsr.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpydXpmcHltemt6ZWdkaG16d3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NjM4MTIsImV4cCI6MjA1NzQzOTgxMn0.fo7-t2T6wbPAyzezvZgFjOmu4hEy3T9f4EpR4JxltL0"

# The service role key should be set as a secret, not in the config file
# Run this command to set it:
# fly secrets set SUPABASE_SERVICE_ROLE_KEY="your-service-role-key"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]
