
[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node src/api/server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[nixpacks]
nodejs = "20"

[[services]]
name = "affiliate-tools"
envs = { NODE_ENV = "production" } 
