
[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node src/api/postback.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[nixpacks]
nodejs = "20"

[[services]]
name = "afftools-api"
envs = { NODE_ENV = "production" } 
